{% set name = "json_schema_validator" %}
{% set version = "2.1.0" %}
{% set sha256 = "83f61d8112f485e0d3f1e72d51610ba3924b179926a8376aef3c038770faf202" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pboettch/json-schema-validator/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nlohmann_json
  run:
    - nlohmann_json

test:
  commands:
    - test -f ${PREFIX}/include/nlohmann/json-schema.hpp  # [unix]
    - test -f ${PREFIX}/lib/libnlohmann_json_schema_validator.so  # [linux]
    - test -f ${PREFIX}/lib/libnlohmann_json_schema_validator.dylib  # [osx]
    - test -f %PREFIX%\Library\include\nlohmann\json-schema.hpp  # [win]
    - test -f %PREFIX%\Library\bin\nlohmann_json_schema_validator.dll  # [win]
    - test -f %PREFIX%\Library\lib\nlohmann_json_schema_validator.lib  # [win]

about:
  home: https://github.com/pboettch/json-schema-validator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON schema validator for JSON for Modern C++

extra:
  recipe-maintainers:
    - JohanMabille
    - asafkahlon
